name: build-main
run-name: build-main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build csv
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install -r requirements.txt

      # install gdal
      - run: sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
      - run: sudo apt-get update
      - run: sudo apt-get install gdal-bin libgdal-dev

      - run: python3 build.py

      - run: python3 -m unittest

      - run: zip gdalsrsinfo.csv.zip gdalsrsinfo.csv

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
